# =========================================================
#  ConfigMap = NE-tajna konfiguracija (sve osim lozinki).
#  Lozinka je odvojena u Secret (03-secret.yaml).
# =========================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketing-config
  namespace: ticketing
  labels:
    app.kubernetes.io/part-of: ticketing-platform
data:
  POSTGRES_DB: "ticketing"
  POSTGRES_USER: "ticketing_user"
  POSTGRES_HOST: "postgres"        # interno ime servisa (DNS unutar namespacea)
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  API_PORT: "8080"
  FRONTEND_PORT: "3000"
  QUEUE_NAME: "ticket_orders"
  NODE_ENV: "production"

 
#ovo je samo primjer, mijenjat ces kad dobijes u 6. koraku nakon naredbe oc -n ticketing get route api. nakon tog stavi taj link ovdje 
  API_BASE_URL: "http://ticketing.local/api"
