#  NetworkPolicy - segmentacija prometa (zero-trust unutar namespacea)

# 1) Default deny svega dolaznog u namespaceu
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: ticketing
spec:
  podSelector: {}            # odnosi se na SVE podove
  policyTypes:
    - Ingress
  # nema 'ingress' pravila -> sav dolazni promet je zabranjen
---
# 2) Postgres prima SAMO od api i worker, na 5432
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-postgres
  namespace: ticketing
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgres
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector: { matchLabels: { app.kubernetes.io/name: api } }
        - podSelector: { matchLabels: { app.kubernetes.io/name: worker } }
      ports:
        - protocol: TCP
          port: 5432
---
# 3) Redis prima SAMO od api i worker, na 6379
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-redis
  namespace: ticketing
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redis
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector: { matchLabels: { app.kubernetes.io/name: api } }
        - podSelector: { matchLabels: { app.kubernetes.io/name: worker } }
      ports:
        - protocol: TCP
          port: 6379
---
# 4) API prima od frontend podova + izvana (Ingress controller) na 8080.

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-api
  namespace: ticketing
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: api
  policyTypes: [Ingress]
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
---
# 5) Frontend prima izvana (Ingress controller) na 3000
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-frontend
  namespace: ticketing
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: frontend
  policyTypes: [Ingress]
  ingress:
    - ports:
        - protocol: TCP
          port: 3000
